#!/usr/bin/env python3
"""Generate the bundled GROMACS port of AmberTools phosaa14SB.

The source OFF library and frcmod file are distributed with AmberTools.  The
generated files are committed, so AmberTools/ParmEd are development-only
dependencies.  Phosphate-specific atom types are renamed here to keep the
frcmod OP Lennard-Jones override local to modified amino acids; otherwise it
would also alter unrelated nucleic-acid OP atoms in the bundled force field.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from parmed.amber import AmberOFFLibrary


TYPE_MAP = {
    "OP": "PHOP", "OQ": "PHOQ", "OR": "PHOR", "OT": "PHOT",
    "OV": "PHOV", "OX": "PHOX", "OZ": "PHOZ", "CG": "PHCG",
}
ATOMIC_NUMBERS = {"OP": 8, "OQ": 8, "OR": 8, "OT": 8, "OV": 8,
                  "OX": 8, "OZ": 8, "CG": 6}
MASSES = {"OP": 16.00, "OQ": 16.00, "OR": 16.00, "OT": 16.00,
          "OV": 16.00, "OX": 16.00, "OZ": 16.00, "CG": 12.01}
SOURCE_RESIDUES = ("S1P", "SEP", "T1P", "TPO", "Y1P", "PTR")
BASE_RESIDUES = {"S1P": "SER", "SEP": "SER", "T1P": "THR",
                 "TPO": "THR", "Y1P": "TYR", "PTR": "TYR"}


def _sections(path: Path) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    current = ""
    for raw in path.read_text().splitlines():
        stripped = raw.strip()
        if stripped in {"MASS", "BOND", "ANGL", "DIHE", "IMPR", "NONB"}:
            current = stripped
            result[current] = []
        elif current and stripped:
            result[current].append(raw.rstrip())
    return result


def _numeric_prefix(line: str, count: int) -> tuple[str, list[float]] | None:
    number = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?"
    values_pattern = r"\s+".join([number] * count)
    match = re.match(rf"^(.+?)\s+({values_pattern})(?:\s|$)", line)
    if not match:
        return None
    return match.group(1), [float(value) for value in match.group(2).split()]


def _types(key: str) -> list[str]:
    return [TYPE_MAP.get(item.strip(), item.strip())
            for item in re.split(r"\s*-\s*", key.strip())]


def _base_impropers(rtp_path: Path) -> dict[str, list[tuple[str, ...]]]:
    wanted = {"SER", "THR", "TYR"}
    result = {name: [] for name in wanted}
    residue = ""
    section = ""
    for raw in rtp_path.read_text().splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            header = line[1:-1].strip()
            if header in {"atoms", "bonds", "angles", "dihedrals", "impropers"}:
                section = header
            else:
                residue = header.upper()
                section = ""
            continue
        if residue in wanted and section == "impropers":
            parts = tuple(line.split())
            if len(parts) >= 4:
                result[residue].append(parts)
    return result


def generate_rtp(off_path: Path, base_rtp: Path) -> str:
    templates = AmberOFFLibrary.parse(str(off_path))
    impropers = _base_impropers(base_rtp)
    lines = [
        "; AmberTools phosaa14SB residue topologies for ff14SB",
        "; Source: phosaa14SB.lib (Homeyer et al., J Mol Model 2006, 12, 281-289)",
        "; Generated by tools/import_amber14sb_phosaa.py; do not edit manually.",
        "",
    ]
    for name in SOURCE_RESIDUES:
        residue = templates[name]
        improper_aliases = {"OH": "OG"} if name == "Y1P" else {}
        lines.extend((f"[ {name} ]", " [ atoms ]"))
        for group, atom in enumerate(residue.atoms, start=1):
            atom_type = TYPE_MAP.get(atom.type, atom.type)
            lines.append(
                f"  {atom.name:<6s} {atom_type:<6s} {atom.charge:14.6f} {group:5d}"
            )
        lines.append(" [ bonds ]")
        for bond in residue.bonds:
            lines.append(f"  {bond.atom1.name:<6s} {bond.atom2.name:<6s}")
        lines.append("  -C     N")
        lines.append(" [ impropers ]")
        for improper in impropers[BASE_RESIDUES[name]]:
            translated = tuple(improper_aliases.get(token, token) for token in improper)
            if all(token.lstrip("+-") in {atom.name for atom in residue.atoms}
                   or token.startswith(("+", "-")) for token in translated[:4]):
                lines.append("  " + " ".join(f"{token:<5s}" for token in translated))
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_itp(frcmod_path: Path) -> str:
    sections = _sections(frcmod_path)
    lines = [
        "; AmberTools phosaa14SB parameters for ff14SB",
        "; Source: frcmod.phosaa14SB (Homeyer et al., J Mol Model 2006, 12, 281-289)",
        "; PHO*/PHCG are isolated aliases of the source OP/OQ/OR/OT/OV/OX/OZ/CG types.",
        "; Generated by tools/import_amber14sb_phosaa.py; do not edit manually.",
        "", "[ atomtypes ]",
        "; name  at.num  mass  charge ptype sigma(nm) epsilon(kJ/mol)",
    ]
    nonbonded = {}
    for raw in sections["NONB"]:
        parsed = _numeric_prefix(raw, 2)
        if parsed:
            key, values = parsed
            source_type = key.strip()
            if source_type in TYPE_MAP:
                nonbonded[source_type] = values
    for source_type, mapped in TYPE_MAP.items():
        rmin_half, epsilon = nonbonded[source_type]
        sigma = (2.0 * rmin_half * 0.1) / (2.0 ** (1.0 / 6.0))
        lines.append(
            f"{mapped:>6s} {ATOMIC_NUMBERS[source_type]:7d} {MASSES[source_type]:8.3f} "
            f"0.0000 A {sigma:16.12f} {epsilon * 4.184:16.12f}"
        )

    lines.extend(("", "[ bondtypes ]"))
    for raw in sections["BOND"]:
        parsed = _numeric_prefix(raw, 2)
        if not parsed:
            continue
        key, (k_amber, length_a) = parsed
        atom_types = _types(key)
        if any(item in TYPE_MAP.values() for item in atom_types):
            lines.append(
                f"{atom_types[0]:>6s} {atom_types[1]:>6s} 1 "
                f"{length_a * 0.1:12.8f} {k_amber * 836.8:14.6f}"
            )

    lines.extend(("", "[ angletypes ]"))
    for raw in sections["ANGL"]:
        parsed = _numeric_prefix(raw, 2)
        if not parsed:
            continue
        key, (k_amber, angle) = parsed
        atom_types = _types(key)
        if any(item in TYPE_MAP.values() for item in atom_types):
            lines.append(
                f"{atom_types[0]:>6s} {atom_types[1]:>6s} {atom_types[2]:>6s} 1 "
                f"{angle:12.6f} {k_amber * 8.368:14.6f}"
            )

    lines.extend(("", "[ dihedraltypes ]"))
    for raw in sections["DIHE"]:
        parsed = _numeric_prefix(raw, 4)
        if not parsed:
            continue
        key, (divisor, barrier, phase, periodicity) = parsed
        atom_types = _types(key)
        if any(item in TYPE_MAP.values() for item in atom_types):
            lines.append(
                " ".join(f"{item:>6s}" for item in atom_types)
                + f" 9 {phase:12.6f} {barrier * 4.184 / divisor:14.8f} "
                  f"{abs(int(periodicity)):3d}"
            )
    for raw in sections["IMPR"]:
        parsed = _numeric_prefix(raw, 3)
        if not parsed:
            continue
        key, (barrier, phase, periodicity) = parsed
        atom_types = _types(key)
        if any(item in TYPE_MAP.values() for item in atom_types):
            lines.append(
                " ".join(f"{item:>6s}" for item in atom_types)
                + f" 4 {phase:12.6f} {barrier * 4.184:14.8f} "
                  f"{abs(int(periodicity)):3d}"
            )
    lines.extend((
        "; Isolated-type equivalents of ff14SB aromatic planarity impropers.",
        "; PHCG is the frcmod CG analogue of CA; PHOR/PHOV are bridging-O analogues.",
        "    CA     CA   PHCG     CT 4   180.000000     4.60240000   2",
        "    CA     CA      C   PHOR 4   180.000000     4.60240000   2",
        "    CA     CA      C   PHOV 4   180.000000     4.60240000   2",
    ))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--amber-dat", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    leap = args.amber_dat / "leap"
    output = args.output_dir
    output.mkdir(parents=True, exist_ok=True)
    (output / "phosaa14sb.rtp").write_text(generate_rtp(
        leap / "lib" / "phosaa14SB.lib", output / "aminoacids.rtp"
    ))
    (output / "ffphosaa14sb.itp").write_text(generate_itp(
        leap / "parm" / "frcmod.phosaa14SB"
    ))


if __name__ == "__main__":
    main()
